version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: webpack
    versions:
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.1
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.28.0
    - 5.29.0
    - 5.31.1
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: inversify
    versions:
    - 5.1.0
  - dependency-name: ts-jest
    versions:
    - 26.5.5
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.1.0
  - dependency-name: css-loader
    versions:
    - 5.1.4
    - 5.2.4
  - dependency-name: tsconfig-paths-webpack-plugin
    versions:
    - 3.4.0
    - 3.4.1
    - 3.5.0
  - dependency-name: "@packagaya/ts-adapter"
    versions:
    - 1.5.1
