name: CI Workflow for Botvy

on: [push]

jobs:
    packagaya:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
            - name: Use Node.js 15.x
              uses: actions/setup-node@v1
              with:
                  node-version: 15.x
            - name: Install yarn
              run: npm i -g yarn
            - name: Install the dependencies
              run: yarn install
              shell: bash
            - run: yarn run packagaya sync info
              shell: bash
              env:
                  LOG_LEVEL: debug
