name: Checks if the tests are passing

on:
    push:
        branches-ignore:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Install make
              run: sudo apt-get update && sudo apt-get install -y make
            - name: Checkout the repository
              uses: actions/checkout@v2
            - name: Use Node.js 15.x
              uses: actions/setup-node@v1
              with:
                  node-version: 15.x
            - name: Install yarn
              run: npm i -g yarn
            - name: Install the dependencies
              run: yarn install
              shell: bash
            - name: Run the tests
              run: make ci
              shell: bash
            - name: Upload the code coverage results to codecov
              run: bash <(curl -s https://codecov.io/bash) -f ./coverage/lcov.info
